name: "cache packages list"
on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: data

      - run: curl --remote-name-all https://raw.githubusercontent.com/herodevs/hd-critical-packages/refs/heads/main/npm.json

      - run: jq -jc '.[].Name + "\u0000"' npm.json | xargs -0 -I {} > packages.txt
      - run: rm npm.json

      - run: git diff && git status

      - name: commit changes
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: "update list of packages"
